### ISSUE TITLE
BACKBLAZE_ASSET_HOST

### ISSUE THREAD

**Issue by idkjs** [factsfinder/pheonix_api#1]
Hi @factsfinder. Thank you for sharing this project.

Trying to run it here and I cant seem to figure out the value expected for `BACKBLAZE_ASSET_HOST`. Where are you getting that. I dont see it in the [search results](https://help.backblaze.com/hc/en-us/search?utf8=%E2%9C%93&query=BACKBLAZE_ASSET_HOST&commit=Search) in https://help.backblaze.com.

Also, what args should we provide to `docker-compose run`?

Thanks again.

**Comment by factsfinder** [comment]
Hi @idkjs. 
Its currently used in the config. But I forgot to use the value in .env and manually hardcoded the value. 
Here is the example of value and where you need to use it.
https://github.com/factsfinder/phoenix_api/blob/520714ed7bd0d1102c0288e7c6cadec78f9f00b5/config/config.exs#L43

We don't need to provide any args to docker-compose run.

**Comment by idkjs** [comment]
Ok. Figured those values were duplicated. Will look at it again. Thank you, sir.
